version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
      # This syncs the config file to the container one saving us to do a custom image
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      # Allows us to persist data here 
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
