version: '3'
services:
  node-app:
    build:
      context: .
      # this variables are used in Dockerfile so we need to
      #  pass then so these are available when builting image
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword